apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-server.configMapName" . }}
  labels:
    {{- include "pod-server.labels" . | nindent 4 }}
data:
  CSS_BASE_URL: {{ required "app.baseUrl is required" .Values.app.baseUrl | quote }}
  CSS_CONFIG: /opt/oxfordia-pod/packages/pod-server/config/config.json
  CSS_MAIN_MODULE_PATH: /opt/oxfordia-pod/packages/pod-server
  CSS_ROOT_FILE_PATH: {{ .Values.app.dataPath | quote }}
  CSS_PORT: "3000"
  TRUST_PROXY: {{ ternary "true" "false" .Values.app.trustProxy | quote }}
  {{- if eq .Values.triplestore.mode "managed" }}
  CSS_SPARQL_ENDPOINT: {{ printf "http://%s:%v/blazegraph/sparql" (include "pod-server.blazegraphFullname" .) .Values.triplestore.managed.servicePort | quote }}
  {{- else if eq .Values.triplestore.mode "external" }}
  CSS_SPARQL_ENDPOINT: {{ required "triplestore.external.url is required when triplestore.mode=external" .Values.triplestore.external.url | quote }}
  {{- else }}
  {{- fail "triplestore.mode must be either external or managed" }}
  {{- end }}
  {{- range $key, $value := .Values.css.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
