{{- if .Values.css.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pod-server.secretName" . }}
  labels:
    {{- include "pod-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.css.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
